// Code generated by musgen. DO NOT EDIT.

package pkg2

import "github.com/ymz-ncnk/musgo/errs"

// MarshalCUSTOM fills buf with the MUS encoding of v.
func (v ByteAlias) MarshalCUSTOM(buf []byte) int {
	i := 0
	{
		buf[i] = byte(v)
		i++
	}
	return i
}

// UnmarshalCUSTOM parses the MUS-encoded buf, and sets the result to *v.
func (v *ByteAlias) UnmarshalCUSTOM(buf []byte) (int, error) {
	i := 0
	var err error
	{
		if i > len(buf)-1 {
			return i, errs.ErrSmallBuf
		}
		(*v) = ByteAlias(buf[i])
		i++
	}
	return i, err
}

// SizeCUSTOM returns the size of the MUS-encoded v.
func (v ByteAlias) SizeCUSTOM() int {
	size := 0
	{
		_ = v
		size++
	}
	return size
}
