// Code generated by musgen. DO NOT EDIT.

package pkg3

import (
	"github.com/ymz-ncnk/musgo/errs"
	"github.com/ymz-ncnk/musgotry/pkg1"
)

// MarshalMUS fills buf with the MUS encoding of v.
func (v Struct) MarshalMUS(buf []byte) int {
	i := 0
	{
		si := (*v.InnerStruct).MarshalMUS(buf[i:])
		i += si
	}
	{
		si := v.Map.MarshalMUS(buf[i:])
		i += si
	}
	{
		uv := uint64((*v.num))
		if (*v.num) < 0 {
			uv = ^(uv << 1)
		} else {
			uv = uv << 1
		}
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	{
		{
			buf[i] = byte(v.time)
			i++
			buf[i] = byte(v.time >> 8)
			i++
			buf[i] = byte(v.time >> 16)
			i++
			buf[i] = byte(v.time >> 24)
			i++
			buf[i] = byte(v.time >> 32)
			i++
			buf[i] = byte(v.time >> 40)
			i++
			buf[i] = byte(v.time >> 48)
			i++
			buf[i] = byte(v.time >> 56)
			i++
		}
	}
	return i
}

// UnmarshalMUS parses the MUS-encoded buf, and sets the result to *v.
func (v *Struct) UnmarshalMUS(buf []byte) (int, error) {
	i := 0
	var err error
	v.InnerStruct = new(InnerStruct)
	{
		var sv InnerStruct
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			(*v.InnerStruct) = sv
			i += si
			err = NotEmptyInnerStruct(v.InnerStruct)
		}
	}
	if err != nil {
		return i, errs.NewFieldError("InnerStruct", err)
	}
	{
		var sv pkg1.ValidMapAlias
		si := 0
		si, err = sv.UnmarshalMUS(buf[i:])
		if err == nil {
			v.Map = sv
			i += si
		}
	}
	if err != nil {
		return i, errs.NewFieldError("Map", err)
	}
	v.num = new(int)
	{
		var uv uint64
		{
			if i > len(buf)-1 {
				return i, errs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 9 && b > 1 {
					return i, errs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint64(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint64(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, errs.ErrSmallBuf
			}
		}
		if uv&1 == 1 {
			uv = ^(uv >> 1)
		} else {
			uv = uv >> 1
		}
		(*v.num) = int(uv)
	}
	if err != nil {
		return i, errs.NewFieldError("num", err)
	}
	{
		{
			if len(buf) < 8 {
				return i, errs.ErrSmallBuf
			}
			v.time = int64(buf[i])
			i++
			v.time |= int64(buf[i]) << 8
			i++
			v.time |= int64(buf[i]) << 16
			i++
			v.time |= int64(buf[i]) << 24
			i++
			v.time |= int64(buf[i]) << 32
			i++
			v.time |= int64(buf[i]) << 40
			i++
			v.time |= int64(buf[i]) << 48
			i++
			v.time |= int64(buf[i]) << 56
			i++
		}
	}
	if err != nil {
		return i, errs.NewFieldError("time", err)
	}
	return i, err
}

// SizeMUS returns the size of the MUS-encoded v.
func (v Struct) SizeMUS() int {
	size := 0
	{
		ss := (*v.InnerStruct).SizeMUS()
		size += ss
	}
	{
		ss := v.Map.SizeMUS()
		size += ss
	}
	{
		uv := uint64((*v.num)<<1) ^ uint64((*v.num)>>63)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	{
		{
			_ = v.time
			size += 8
		}
	}
	return size
}
